version: '3.8'

services:
  app:
    container_name: "${CONTAINER_NAME}"
    image: "${IMAGE_NAME}-dev"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8080"
    env_file:
      - ./.env

